spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:db-port/eventostec
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true